### ISSUE TITLE
引入js文件报错

### ISSUE THREAD

**Issue by 18465139686** [alberto-acevedo/cesium-navigation#55]
您好，为什么我引入这个js文件报错呢？？
报错：**Uncaught ReferenceError: define is not defined**     at VM300680 viewerCesiumNavigationMixin.js:5:1
引入方式：
index.html
`<head>
<script src="./static/js/Source/viewerCesiumNavigationMixin.js"></script>
</head>`
就报这个文件里面不知道什么错，我是使用的是vue2.0写的

**Comment by LLJJTT** [comment]
我也是静态文件引入错误：Uncaught ReferenceError: define is not defined
    at viewerCesiumNavigationMixin.js:5:1
